### ISSUE TITLE
erre

### ISSUE THREAD

**Issue by cqrlhz** [f0ng/captcha-killer-modified#33]
c1JNSYn4vRoDAkDmUS7Z9euIBtn1SgYApGkAEEbDAEhGIqolGgCQaNA+NNdoVtnbLxTCY+mlU6F2Ww6AdaLkrjBoy6kMj3lMZRROMtNhNkwQBqgxGoj3VVLCWFVzmQwBIBsfXspooFmPmA3T7CqnJDMoN6pJJiEHRGGoBA8g3uFDaRwQAI2KWCEAwsniUcyGCdVRkpmOIob5jiyApglWNpRdZRhrAvARiWqFNF2yXZMkdmyB624yCwDmkwwxqkmZlApfVzykoiw2vsFmW+TlCJC1WVCfFoFRjkFv2lASDQQAqjAorw3TMUur/TxPUmvXOgAoNZ9kAKzKgBgVSVCW4hypdgxEBAapEJAnrPMdWZkBACRo5cdY1ENcT4zpWLEM8C08AGXLeZTk1no+vG4G80lmPsmY3YOyXbGbHAfOYFJZJ6QET1lslMWmDItGXi/nImKHk52y35U2Vko0qRCk5X8B2dbo0rijeKoAAAAASUVORK5CYII=
Error handling request
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\captcha-killer-modified-main\codereg.py", line 26, in handle_cb
    return web.Response(text=ocr.classification(img_bytes)[0:4])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ddddocr\__init__.py", line 466, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
                                                                          ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by f0ng** [comment]
参考https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#17-%E6%8A%A5%E9%94%99module-pilimage-has-no-attribute-antialias
