### ISSUE TITLE
报错无法解决，大佬们帮帮忙

### ISSUE THREAD

**Issue by HHHHDDDDD222** [f0ng/captcha-killer-modified#53]
欢迎使用ddddocr，本项目专注带动行业内卷，个人博客:wenanzhe.com
训练数据支持来源于:http://146.56.204.113:19199/preview
爬虫框架feapder可快速一键接入，快速开启爬虫之旅：https://github.com/Boris-code/feapder
谷歌reCaptcha验证码 / hCaptcha验证码 / funCaptcha验证码商业级识别接口：https://yescaptcha.com/i/NSwk7i
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<_run_app() done, defined at /usr/local/lib/python3.10/dist-packages/aiohttp/web.py:303> exception=TypeError('The port is required to be int.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 544, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 451, in _run_app
    names = sorted(str(s.name) for s in runner.sites)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 451, in <genexpr>
    names = sorted(str(s.name) for s in runner.sites)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_runner.py", line 112, in name
    return str(URL.build(scheme=scheme, host=host, port=self._port))
  File "/usr/local/lib/python3.10/dist-packages/yarl/_url.py", line 237, in build
    raise TypeError("The port is required to be int.")
TypeError: The port is required to be int.
Traceback (most recent call last):
  File "/home/ubuntu/burp验证码识别/codereg.py", line 73, in <module>
    web.run_app(app, port=port)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 544, in run_app
    loop.run_until_complete(main_task)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 451, in _run_app
    names = sorted(str(s.name) for s in runner.sites)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web.py", line 451, in <genexpr>
    names = sorted(str(s.name) for s in runner.sites)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_runner.py", line 112, in name
    return str(URL.build(scheme=scheme, host=host, port=self._port))
  File "/usr/local/lib/python3.10/dist-packages/yarl/_url.py", line 237, in build
    raise TypeError("The port is required to be int.")
TypeError: The port is required to be int.
报错，是为啥啊

**Comment by HHHHDDDDD222** [comment]
好的已经解决了，原因是缺少一个库

**Comment by linjiananallnt** [comment]
原：
web.run_app(app, port=port)
改：
web.run_app(app, port=int(port))
需要强制换成int类型

**Comment by f0ng** [comment]
参考 https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#19-the-port-is-required-to-be-int
